const ruKeys = [
  'global_id',
  'Название спортивного объекта',
  'Название спортивной зоны в зимний период',
  'Административный округ',
  'Район',
  'Адрес',
  'Адрес электронной почты',
  'Адрес сайта',
  'Справочный телефон',
  'Добавочный номер',
  'График работы в зимний период',
  'Уточнение графика работы в зимний период',
  'Возможность проката оборудования',
  'Комментарии для проката оборудования',
  'Наличие сервиса технического обслуживания',
  'Комментарии для сервиса технического обслуживания',
  'Наличие раздевалки',
  'Наличие точки питания',
  'Наличие туалета',
  'Наличие точки Wi-Fi',
  'Наличие банкомата',
  'Наличие медпункта',
  'Наличие звукового сопровождения',
  'Период эксплуатации в зимний период',
  'Размеры в зимний период',
  'Освещение',
  'Покрытие в зимний период',
  'Количество оборудованных посадочных мест',
  'Форма посещения (платность)',
  'Комментарии к стоимости посещения',
  'Приспособленность для занятий инвалидов',
  'Услуги предоставляемые в зимний период',
  'geoData',
  'geodata_center',
];

const enKeys = [
  'global_id',
  'ObjectName',
  'NameWinter',
  'AdmArea',
  'District',
  'Address',
  'Email',
  'WebSite',
  'HelpPhone',
  'HelpPhoneExtension',
  'WorkingHoursWinter',
  'ClarificationOfWorkingHoursWinter',
  'HasEquipmentRental',
  'EquipmentRentalComments',
  'HasTechService',
  'TechServiceComments',
  'HasDressingRoom',
  'HasEatery',
  'HasToilet',
  'HasWifi',
  'HasCashMachine',
  'HasFirstAidPost',
  'HasMusic',
  'UsagePeriodWinter',
  'DimensionsWinter',
  'Lighting',
  'SurfaceTypeWinter',
  'Seats',
  'Paid',
  'PaidComments',
  'DisabilityFriendly',
  'ServicesWinter',
  'geoData',
  'geodata_center',
];
